#!/usr/bin/env ansible-playbook --ask-vault-pass
# vim:ft=ansible :
#
# Ansible playbook to manage servers
#

---

- name: ensure that server is setup and hardened
  hosts: "{{ target | default('all') }}"
  remote_user: root
  gather_facts: no

  vars:
    admins_email: craftsman@bendoerr.me
    sender_email: "{{ inventory_hostname_short }}@cloud.bendoerr.com"

    dma_smarthost:  gateway.internal.cloud.bendoerr.com
    dma_mailname:   "{{ inventory_hostname }}"
    dma_masquerade: "{{ sender_email }}"

    fail2ban_destemail: "{{ admins_email }}"
    fail2ban_sender:    "{{ sender_email }}"

    users_sudoers_mailto:   "{{ admins_email }}"
    users_sudoers_mailfrom: "{{ sender_email }}"

    host_certs_admin_email: "{{ admins_email }}"

  vars_files:
    - vars/dkim.yml.vault
    - vars/tripwire.yml.vault
    - vars/users.yml.vault

  roles:

    - role: find_port
      tags: always

    - role: fqdn
      tags: fqdn

    - role: sshd
      tags: sshd

    - role: host_certs
      tags: host_certs

    - role: dragonfly-mail-agent
      tags: mta
      when: "'mail-relays' not in group_names"

    - role: relay-mail-agent
      tags: mta
      when: "'mail-relays' in group_names"

    - role: fail2ban
      tags: fail2ban

    - role: vim
      tags: vim

    - role: users
      tags: users

    - role: tripwire
      tags: tripwire

    - role: do-agent
      tags: do-agent

    - role: docker
      tags: docker
      when: "'docker-host' in group_names"
