# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box =     "ubuntu/xenial64"
  config.vm.network   "public_network", bridge: "en1: Wi-Fi (AirPort)"
  config.vm.provider  "virtualbox"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end

end
