# vim:ft=ansible :
#
# Ansible role to install Docker
#

---

- name: add docker apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present


- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
    filename: download_docker_com_linux_ubuntu


- name: install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
